### ISSUE TITLE
Camera integration

### ISSUE THREAD

**Issue by dodie** [dodie/tracing-paper-sketching#1]
The app currently only supports picking an image from a Gallery. Extend it, so the user can use the camera to take images, and use those in the app.

Add a new "Camera" button to the main screen, below the "Pick an image" button. When the user clicks it, open the camera app. When a photo is taken, load it into the canvas.

![image](https://user-images.githubusercontent.com/1114220/65692675-3b2a4e80-e073-11e9-9769-25b440a22144.png)

**Comment by mixon00** [comment]
I added PR #10

**Comment by dodie** [comment]
Works nicely, merged! Thank you!
