### ISSUE TITLE
Typescript

### ISSUE THREAD

**Issue by dodie** [dodie/tracing-paper-sketching#102]
Add Typescript to the project, convert source files to be typescript.

The application should compile and work as before.

**Comment by dodie** [comment]
Hi @jbrigitta ,
Thanks! Let me know if I can help with anything 👍

**Comment by dodie** [comment]
Thanks @jbrigitta , works like a charm!

**Comment by jbrigitta** [comment]
Yeyy, cool! Thanks for the feedback!
