### ISSUE TITLE
Maximize brightness toggle

### ISSUE THREAD

**Issue by dodie** [dodie/tracing-paper-sketching#12]
Add a feature to maximize brightness to aid drawing.

Add a button to the lower-left corner of the canvas that would be used to temporarily maximize brightness. The button should have 2 states:

- Inactive: use default screen brightness (tap to activate)
- Active: use max screen brightness (tap to deactivate)

![image](https://user-images.githubusercontent.com/1114220/66706617-45b43b80-ed35-11e9-869f-5211ee8ce541.png)

**Comment by runningdeveloper** [comment]
I'm going to give this feature a shot

**Comment by dodie** [comment]
Awesome!
