### ISSUE TITLE
Translate the app to German

### ISSUE THREAD

**Issue by dodie** [dodie/tracing-paper-sketching#14]
Translate the app to German by creating a de.json language file based on the [existing translations](https://github.com/dodie/tracing-paper-sketching/tree/master/i18n/translations), and registering it in the [i18n.js](https://github.com/dodie/tracing-paper-sketching/blob/master/i18n/i18n.js).

**Comment by Ryuno-Ki** [comment]
I'd pick this up.
I'm using Android on my own + am German native speaker + web dev by trade.
However, I am not using Google services. How would I check that the translation is working?

**Comment by Ryuno-Ki** [comment]
(on a side note: Did you know, that by hitting <kbd>y</kbd> you could [get a permalink](https://help.github.com/en/articles/keyboard-shortcuts#source-code-browsing) of a file? Could be helpful if you want to figure out later on what an issue was about. Feel free to flag this comment as Off-Topic).

**Comment by dodie** [comment]
Hey @Ryuno-Ki !

Sorry for the delay. I've already merged a [German translation](https://github.com/dodie/tracing-paper-sketching/blob/48cfc4d3023f12cc6ed1e54a357f4c05338a8880/i18n/translations/de.json). Could you please check if it can be improved?

(Thanks for the tip, using permalinks in issues indeed helps consistency!)

Cheers,
David

**Comment by Ryuno-Ki** [comment]
The translation is using formal language, but looks okay.

Glad I could at least help with something.

**Comment by dodie** [comment]
Thank you!
