### ISSUE TITLE
Translate the app to Spanish

### ISSUE THREAD

**Issue by dodie** [dodie/tracing-paper-sketching#16]
Translate the app to Spanish by creating an es.json language file based on the [existing translations](https://github.com/dodie/tracing-paper-sketching/tree/master/i18n/translations), and registering it in the [i18n.js](https://github.com/dodie/tracing-paper-sketching/blob/master/i18n/i18n.js).

**Comment by vherasme** [comment]
Hello. Can I take care of this?

**Comment by RockLee444** [comment]
Hey. Is this still open?

**Comment by dodie** [comment]
Hey ,
Thanks for the interest! The translation is now merged to master, thanks @vherasme ! 
Cheers,
David
