### ISSUE TITLE
Translate the app to Czech

### ISSUE THREAD

**Issue by dodie** [dodie/tracing-paper-sketching#18]
Translate the app to Czech by creating a cz.json language file based on the [existing translations](https://github.com/dodie/tracing-paper-sketching/tree/master/i18n/translations), and registering it in the [i18n.js](https://github.com/dodie/tracing-paper-sketching/blob/master/i18n/i18n.js).

**Comment by bharrod321** [comment]
Created PR for this.

**Comment by dodie** [comment]
Thanks!
