### ISSUE TITLE
Translate the app to Russian

### ISSUE THREAD

**Issue by dodie** [dodie/tracing-paper-sketching#19]
Translate the app to Russian by creating a ru.json language file based on the [existing translations](https://github.com/dodie/tracing-paper-sketching/tree/master/i18n/translations), and registering it in the [i18n.js](https://github.com/dodie/tracing-paper-sketching/blob/master/i18n/i18n.js).

**Comment by EuV** [comment]
Hi!

I'll work on it.

**Comment by dodie** [comment]
Hey @EuV ,

Thanks, it's awesome!

Cheers,
David
