### ISSUE TITLE
Use volume control to lock/unlock

### ISSUE THREAD

**Issue by dodie** [dodie/tracing-paper-sketching#3]
In addition to the unlock button presented at the lower right corner of the canvas, allow locking/unlocking with the physical volume control buttons of the phone.

![image](https://user-images.githubusercontent.com/1114220/65700635-45067e80-e080-11e9-869d-348fc2b5f3ce.png)

**Comment by dbalakirev** [comment]
Mind if I give this a go? :)

**Comment by dodie** [comment]
Absolutely not! :+1: please let me know if I can be any help setting up the project.
