### ISSUE TITLE
Translate the app to Mandarin Chinese

### ISSUE THREAD

**Issue by dodie** [dodie/tracing-paper-sketching#42]
Translate the app to Mandarin Chinese by creating a zh.json language file based on the [existing translations](https://github.com/dodie/tracing-paper-sketching/tree/master/i18n/translations), and registering it in the [i18n.js](https://github.com/dodie/tracing-paper-sketching/blob/master/i18n/i18n.js).

**Comment by alexismo** [comment]
Happy to take this on.

**Comment by dodie** [comment]
Hi @alexismo, awesome, thanks!
