### ISSUE TITLE
Translate the app to Hindi

### ISSUE THREAD

**Issue by dodie** [dodie/tracing-paper-sketching#43]
Translate the app to Hindi by creating a hi.json language file based on the [existing translations](https://github.com/dodie/tracing-paper-sketching/tree/master/i18n/translations), and registering it in the [i18n.js](https://github.com/dodie/tracing-paper-sketching/blob/master/i18n/i18n.js).

**Comment by Abhijit-Dixit** [comment]
I would like to contribute to it, Hindi being my mother tongue language.

**Comment by dodie** [comment]
Hi @Abhijit-Dixit , Thank you!

**Comment by amgusain** [comment]
Tried to add the translations in hindi. Please review https://github.com/dodie/tracing-paper-sketching/pull/50

**Comment by dodie** [comment]
Thank you for your contributions @Abhijit-Dixit and @amgusain !
