### ISSUE TITLE
Translate the app to French

### ISSUE THREAD

**Issue by dodie** [dodie/tracing-paper-sketching#44]
Translate the app to French by creating a fr.json language file based on the [existing translations](https://github.com/dodie/tracing-paper-sketching/tree/master/i18n/translations), and registering it in the [i18n.js](https://github.com/dodie/tracing-paper-sketching/blob/master/i18n/i18n.js).

**Comment by ikayz** [comment]
I want to take this issue

**Comment by dodie** [comment]
Fixed by #49. Thanks!
