### ISSUE TITLE
Translate the app to Arabic

### ISSUE THREAD

**Issue by dodie** [dodie/tracing-paper-sketching#45]
Translate the app to Arabic by creating an ar.json language file based on the [existing translations](https://github.com/dodie/tracing-paper-sketching/tree/master/i18n/translations), and registering it in the [i18n.js](https://github.com/dodie/tracing-paper-sketching/blob/master/i18n/i18n.js).

**Comment by hendaoui** [comment]
Assign it to me :)

**Comment by dodie** [comment]
Hi @hendaoui , Thanks!
