### ISSUE TITLE
Translate the app to Indonesian

### ISSUE THREAD

**Issue by dodie** [dodie/tracing-paper-sketching#47]
Translate the app to Indonesian by creating an id.json language file based on the [existing translations](https://github.com/dodie/tracing-paper-sketching/tree/master/i18n/translations), and registering it in the [i18n.js](https://github.com/dodie/tracing-paper-sketching/blob/master/i18n/i18n.js).

**Comment by wincentrtz** [comment]
I can help with Indonesian.
@dodie

**Comment by dodie** [comment]
Hi @wincentrtz , Thanks!

**Comment by wincentrtz** [comment]
Anyway, I'm new with open source and want to make sure something :
- I fork this repository
- Make a branch called feature/indonesian-i18n
- Commit to this branch 
- Make a pull req

is it correct?

**Comment by dodie** [comment]
Yes, this is the way to go :+1:

**Comment by wincentrtz** [comment]
Hi @dodie 
I have finished it please checked my pull req on #55

**Comment by dodie** [comment]
Hi @wincentrtz , Thank you, merged!
