### ISSUE TITLE
Button labels

### ISSUE THREAD

**Issue by dodie** [dodie/tracing-paper-sketching#5]
Currently most buttons are made of simple icons:

![image](https://user-images.githubusercontent.com/1114220/65693978-6a41bf80-e075-11e9-8292-08d4e23783d2.png)

Enhance them so they show helpful but unobtrusive messages next to the buttons to describe their intention:

![image](https://user-images.githubusercontent.com/1114220/65694177-b4c33c00-e075-11e9-9c96-15b213210992.png)

**Comment by mixon00** [comment]
Hi @dodie. I can take this issue.

**Comment by dodie** [comment]
Hi @mixon00,

Awesome! Please let me know if you need any additional information.

Thanks, 
David

**Comment by mixon00** [comment]
I create PR #8

**Comment by dodie** [comment]
Merged, thank you!
