### ISSUE TITLE
Support translation for all strings

### ISSUE THREAD

**Issue by alexismo** [dodie/tracing-paper-sketching#56]
Some strings within the app do not support i18n.
All strings contained within `ActionButton` have a hardcoded `text` prop and are not being translated.

**Comment by dodie** [comment]
Thanks for catching this issue! Indeed, All `ActionButtons` defined [App.js](https://github.com/dodie/tracing-paper-sketching/blob/199744161313cfa89300e667a8688e833c80c6cd/App.js) still have hard-coded Strings, which is not correct.
