### ISSUE TITLE
Add missing translations

### ISSUE THREAD

**Issue by dodie** [dodie/tracing-paper-sketching#59]
Certain texts in the application are not translated to all languages.

Task:
- check the currently used localization keys in [en.json](https://github.com/dodie/tracing-paper-sketching/blob/master/i18n/translations/en.json)
- find your language amongst the [other translation files](https://github.com/dodie/tracing-paper-sketching/blob/master/i18n/translations/), and add the missing translations.

**Comment by Nythiennzo** [comment]
Hello, I sent a Pull Request (#63 ) for the French translation. Is it okay?

**Comment by dodie** [comment]
Hi @Nythiennzo! Yes, thanks!

**Comment by fcosueza** [comment]
Can I complete the spanish file ?

**Comment by dodie** [comment]
hi @fcosueza , thank you! :beers:

**Comment by deividynegri** [comment]
Added a PT-BR translation , please take a look (:

**Comment by dodie** [comment]
Thank you @GEveloper , @deividynegri !
