### ISSUE TITLE
Localize app

### ISSUE THREAD

**Issue by dodie** [dodie/tracing-paper-sketching#6]
Currently, all the text content used in the app is hard-coded ([example](https://github.com/dodie/tracing-paper-sketching/blob/master/App.js#L47)).

Introduce Expo's Localization ([documentation](https://docs.expo.io/versions/latest/sdk/localization/)) module to allow translation to other languages.

**Comment by mixon00** [comment]
@dodie I can resolve this issue too

**Comment by dodie** [comment]
Hey @mixon00 ,

Thanks for all the contributions, I've merged all the PR's!

Cheers,
David
