### ISSUE TITLE
Maximize contrast image transformation

### ISSUE THREAD

**Issue by dodie** [dodie/tracing-paper-sketching#62]
Add a feature to enhance the loaded image with maximum contrast. This might make tracing the image easier.

Goals:
- when the user taps on the button, the loaded image should be presented in a high contrast version
- a consequent tap would change the image to show it's original contrast

Add the new button to the lower-left corner of the canvas, next to the `mirror` button (align the buttons vertically).

![image](https://user-images.githubusercontent.com/1114220/66706617-45b43b80-ed35-11e9-869f-5211ee8ce541.png)

Additional idea: button to invert the colors of the image.

**Comment by dodie** [comment]
For ideas see #61 .

**Comment by PapGeri** [comment]
I would like to give this a try!

**Comment by dodie** [comment]
I'm closing this issue and merging the idea to #61.
